# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

# Define services
services:
  # AuthZ service
  app-server:
    # Configuration for building the docker image for the backend service
    image: luigiferrettino/custom-oauth:authz
    ports:
      - "9080:9080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always 
    networks:
        testing_net:
            ipv4_address: 172.28.1.2
  
  # Resource service
  app-res:
    # Configuration for building the docker image for the backend service
    image: luigiferrettino/custom-oauth:resource
    ports:
      - "9280:9280" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always 
    depends_on: 
      - app-server
    networks:
        testing_net:
            ipv4_address: 172.28.1.3

  # Client Service 
  app-client:
    image: luigiferrettino/custom-oauth:client
    ports:
      - "9180:9180" # Map the exposed port 9190 on the container to port 9190 on the host machine
    restart: always
    depends_on:
      - app-res
    networks:
        testing_net:
            ipv4_address: 172.28.1.1


# Networks to be created to facilitate communication between containers
networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16